### ISSUE TITLE
Project sound like fun

### ISSUE THREAD

**Issue by SteveTeece** [pjlplourde/UnitConversionApp#1]
I've been meaning to create one of these for ages, but never got around to it.  I'd love to help you.  Have you done any planning for your models and library interfaces?

**Comment by mikey32905** [comment]
This was one of my first choices for a project.   I do a lot of "unit conversions" for the project I am working on at my job.   I would love to help.

**Comment by pjlplourde** [comment]
@SteveTeece I just created the basic scaffolding for the data models and the converter class, along with the unit test class, this morning.
